### ISSUE TITLE
Kafka installation problems in ARM64

### ISSUE THREAD

**Issue by fiv21** [NVIDIA-AI-IOT/deepstream-occupancy-analytics#2]
Hi!
I'm having some problems to install Kafka in ARM64, I recommend to use the Kafka server in a docker image in x86/x64 machine.
It will simplify the use case for Jetson devices.
Hope you find this useful.
Best regards,

Franco.

**Comment by fiv21** [comment]
Just in case someone else need the kafka server in a x86/x64 machine and don't want to install by hand, I use this docker compose file

```
version: "2"

services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: 192.168.88.11
      ADVERTISED_PORT: 9092
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    networks:
      - kafkanet
    ports:
      - 9000:9000
    links:
      - kafkaserver
    environment:
      ZK_HOSTS: "192.168.88.11:2181"

networks:
  kafkanet:
    driver: bridge
```

where 192.168.88.11 is the private IP in one of the NICs in my computer connected to the same network of my Jetson Xavier to stablish the communication. From here, supose you named this file  docker-compose.yml you need to build it and this can be done executing in your shell (terminal/powershell/etc...) `docker-compose up -d` (here the troubleshooting should be docker compose, or something related to that)
After your server is up and running you can follow the guide provided in this repo from the point of creating the topic with the command:
`bin/kafka-topics.sh --create --topic quickstart-events --bootstrap-server 192.168.88.11:9092`
where I change the ip for my case to match with the one where I exposed the service.
Keep in mind this to solve the scenarios where you want to test the solution in a Jetson Device and you don't have a Kafka server already installed.
I hope you find this helpful.
All the best,


Franco
